### ISSUE TITLE
Use the same variable name for SmartWallet.factory

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/EigenLayer-AVS#66]
Currently we use different name, `GetWalletResp.AsObject.factoryAddress` and `SmartWallet.factory` to represent the same value, and I think we should settle down a name for both.

Additionally, is it possible to set the `GetWalletResp` to be the same as `SmartWallet` since they are the same object?

Regardless, I have converted the variable names explicitly to `factory` in sdk-js, so it’s a low-pri. 

```
export namespace GetWalletResp {
    export type AsObject = {
        address: string,
        salt: string,
        factoryAddress: string,
    }
}
```

```
export namespace SmartWallet {
    export type AsObject = {
        address: string,
        salt: string,
        factory: string,
    }
}
```

**Comment by v9n** [comment]
Sure, we can change. I'm not sure if it's a good idea.

One is when you get a single wallet.  Other is when you get a list of wallet. Right now they look identical, tomorrow they might not. Such as when we add the task count. Get a single wallet we can return more information, but when return a list we probably want it to be as trim as possible.

![CleanShot 2024-12-11 at 20 53 46](https://github.com/user-attachments/assets/9d1e199a-000a-43e6-b210-4b0d9537091b)

![CleanShot 2024-12-11 at 20 55 30](https://github.com/user-attachments/assets/d0e6845a-8856-4275-9106-fd45d3f39867)

For the history, it evolve as below:

1. Originally List return a list of SmartWallet as it's right now.
2. CreateWallet just return the address only because we had all the information when we submit the request. Then you requested a chance  to make Create return the same information as ListWallet. That's why they look identical but they are fundamental different context.
3. Then you request to change CreateWallet -> GetWallet. And that's where we ended up now.

To return the count, we scan the key prefix (without reading the data), just scan the key and count so it's efficient. But still don't want to do this count for a list. Or we have to store a counter and manage this counter when we add/delete/cancel. each has pros and cons. But regardless, I'm in the camp of List we will returm summary information. Get we will return all relevant detail.

And I can imagine eventually we will want to bundle more information into the Get down the line.

That's why I _think_ we should keep them separate instead of converting them into the same one.

But let me know your final call, these change are easy to made.

**Comment by v9n** [comment]
@chrisli30 Can you let me know what is your final call. These are straighforward to change at this point before those name creep around.

**Comment by chrisli30** [comment]
Okay, then we don’t merge the types.
