### ISSUE TITLE
The TriggerMark variable name does not sound very straight-forward

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/EigenLayer-AVS#67]
Initially I could not understand what is a trigger mark, but reading this line "// TriggerMark is used to populate the `trigger.data` variable." I think we could call it either TriggerMetadata, or TriggerContext. I personally prefer the `TriggerMetadata`.

For example, the updated comments and variable name will look like:
```
// TriggerMetadata represents a lookup we can use to identify when, where, and how a trigger is activated.
// In a block trigger, we will have block_number.
// In an event trigger, we will have the log_index, tx_hash, and block_number.
// In a time-based trigger (cron/fixed time), we will have the epoch.
//
// TriggerMetadata is used to populate the `trigger.data` variable. For example, if this is a transfer
// event, you will have access to trigger1.data.from_address and trigger1.data.value.
message TriggerMetadata {
  uint64 block_number = 1;
  uint64 log_index    = 2;
  string tx_hash      = 3;
  uint64 epoch        = 4;
}
```

**Comment by v9n** [comment]
Yes, let me change. These are easy. But allow me to explain why I do it that way.

To me, TriggerMetadata = the information a user define for their trigger. Such as the condition of the trigger, the name of trigger, the type of trigger.

TriggerMark = A marker (a point) where the trigger occurs. That's why you see the information to help us identify that trigger  event.
